MAP DISPLAY OFF 
BREAK ON 
Write 
Write 
Write          "WELCOME %LOGIN_NAME TO MARS NWE 
NETWORK" 
Write          "YOU ARE PRESENT AT THE HOME OF MARS NWE" 
Write          "WE HOPE YOU WILL ENJOY YOUR TIME WITH US!" 
PAUSE 
WRITE 
WRITE 
WRITE          "GOOD %GREETING_TIME, %LOGIN_NAME" 
WRITE          "TODAY'S DATE: %MONTH_NAME %DAY, %YEAR" 
WRITE          "THE TIME IS: %HOUR: %MINUTE %AM_PM" 
WRITE          "YOU HAVE LOGGED IN FROM STATION: %STATION." 
WRITE 
WRITE 
WRITE          "FILE SERVER: %FILE_SERVER" 
PAUSE 
;GENERIC MAPPINGS (REGULAR) 
;THIS COMMAND SETS UP ACCESS TO THE USERS HOME DIRECTORY.  
;IT ALSO SETS UP ACCESS TO THE SCHOOL WIDE SHARED DIRECTORY.  
IF MEMBER OF "EVERYONE" THEN 
     MAP F:=FS1\SYS: 
     MAP J:=FS1\APPS: 
     MAP K:=FS1\APPS:SHARED\GENERAL\ 
     MAP ROOT M:=FS1\APPS:\HOME\%LOGIN_NAME\ 
     ATTACH FS-CD-1/%LOGIN_NAME 
     SET TMP="c:\dos" 
     MAP G:=FS-CD-1\BCD2: 
     MAP H:=FS-CD-1\VOL3: 
     MAP I:=FS-CD-1\95049: 
     MAP N:=FS-CD-1\VOL2:INFOTRAC 
     MAP O:=FS-CD-1\960312A: 
     MAP P:=FS-CD-1\SOFTKEY: 
END 
IF LOGIN_NAME="SUPERVISOR" THEN 
     MAP ROOT M:=FS1_1\APPS:HOME\WARREN 
END      
IF MEMBER OF "SALES" THEN 
     MAP L:=FS1_1\APPS:SHARED\DEPARTMN END 
IF MEMBER OF "IS" THEN 
     MAP L:=FS1_1\APPS:SHARED\DEPARTMN 
END 
IF MEMBER OF "TRAINING" THEN 
     MAP L:=FS1_1\APPS:SHARED\DEPARTMN 
END 
IF MEMBER OF "MANAGEMENT" THEN 
     MAP L:=FS1_1\APPS:SHARED\DEPARTMN 
END 
IF MEMBER OF "ADVERTISING" THEN 
     MAP L:=FS1_1\APPS:SHARED\DEPARTMN 
END 
IF MEMBER OF "ACCOUNTING" THEN 
     MAP L:=FS1_1\APPS:SHARED\DEPARTMN 
END 
IF MEMBER OF "SUPPORT" THEN 
     MAP L:=FS1_1\APPS:SHARED\DEPARTMN 
END 
IF MEMBER OF "OFFICE" THEN 
     MAP L:=FS1_1\APPS:SHARED\DEPARTMN 
END 
IF MEMBER OF "SERVICE" THEN  
     MAP L:=FS1_1\APPS:SHARED\DEPARTMN 
END 
IF MEMBER OF "FACULTY" THEN 
     MAP L:=FS1_1\APPS:SHARED\DEPARTMN 
END 
IF MEMBER OF "EXECUTIVES" THEN  
     MAP L:=FS1_1\APPS:SHARED\DEPARTMN 
END 
;IF MEMBER OF "3WS" THEN 
;     MAP L:=FS1-CD-1\95049: 
;END 
WRITE 
WRITE 
WRITE 
;GENERIC MAPPINGS (SEARCH) 
     MAP INS S1:=SYS:PUBLIC 
;THIS COMMAND SETS UP ACCESS TO DOS ON THE NETWORK 
;MAP INS S2:=C:\ 
;COMSPEC=S2:COMMAND.COM 
;GENERIC SEARCH MAPPING TO HOME DIRECTORY 
     MAP INS S3:=M: 
;GENERIC SEARCH MAPPING TO PEGASUS MAIL 
     MAP S16:=APPS:APPS\EMAIL\PEGASUS ;GENERIC SEARCH MAPPING TO AUTOMENU 
     MAP S16:=APPS:AUTOMENU 
;GENERIC SEARCH MAPPING TO WORDPERFECT 5.1 
     MAP S16:=APPS:APPS\WP\WP51 
;GENERIC SEARCH MAPPING TO QUATTRO PRO V 
     MAP S16:=APPS:APPS\SS\QPRO 
WRITE 
WRITE 
WRITE 
;IF MEMBER OF "3WS" THEN 
;    MAP INS S16:=SYS:TOOLS\LANSKOOL 
;    #TEACHER QUIET 
END 
IF MEMBER OF "APPLIED" THEN 
     MAP INS S16:=SYS:TOOLS\LANSKOOL 
     #STUDENT QUIET 
END 
IF MEMBER OF "3WS" THEN 
     MAP I:=FS1_1/INTERNET: 
     MAP L:=FS1-CD-1/95049: 
END 
WRITE 
;THIS ESTABLISHES A SEARCH PATH TO THE GRADEBOOK 
IF MEMBER OF "GRADEBOOK" THEN 
     MAP INS S4:=APPS:GRADE2NW 
END 
WRITE 
WRITE 
WRITE 
WRITE 
IF DAY_OF_WEEK="FRIDAY" THEN 
WRITE "HANG IN THERE!  THE WEEKEND IS COMING!" 
END 
PAUSE 
FIRE PHASERS 4 TIMES 
WRITE 
WRITE 
;THESE ARE THE SETUPS FOR THE PSERVER AND RPRINTER STATIONS  
;ACCORDING TO LOGIN_NAME 
IF LOGIN_NAME="PRINTSERV1" THEN #SYS:PUBLIC\PSERVER.EXE ROOM125_PS 
END 
WRITE 
WRITE 
WRITE 
WRITE 
;EVENTUALLY REMOVE WISECRAK LINE AND PUT IN CLOSING BAT FILE TO  ;INCLUDE MENU AND VIRUS SCAN OF LOCAL HARDDRIVE.  
;ALSO INCLUDE WSUPDATE LINE WITH # TO UPDATE FPROT. 
;# SYS:PUBLIC\WISECRAK\WISECRAK.EXE 
WRITE 
WRITE 
WRITE 
WRITE 
WRITE 
WRITE 
WRITE 
PAUSE 
DRIVE M: 
IF P_STATION="0040333119DD" THEN 
     EXIT "FS1_2.BAT" 
END 
IF P_STATION<>"0040333119DD" THEN 
     EXIT "FS1_1.BAT" 
END 
;EXIT "FS1_1.BAT" 